### ISSUE TITLE
Discussion: midi/handler API

### ISSUE THREAD

**Issue by kisielk** [gomidi/midi#6]
Hey @metakeule, just responding based on your issue to portmidi. I'm really interested in this because I've been privately working on some of my own MIDI library code, and have also written a C++ MIDI handling framework which I use in my day job...

So far I've had time to review `midi/handler`. The API is looking really good, very well thought out!

 My one quibble is with the `Logger` interface. Why not have the logger take a `midi.Message` and an `SMFPosition` instead? It would allow for much more flexible logging.

Another thing that's not clear to me is why some functions in this package are accepting `SMFPosition` whereas others take `*SMFPosition`? Why pass it by pointer?

**Comment by metakeule** [comment]
Hi  @kisielk,

thanks for taking the time for a review and pointing me to issues regarding the midihandler API.

Did you see the "Status" section in the `README.md`? There the midihandler subpackage API is declared unstable and here is why:

The "core" packages are the packages in the stability table that appear above the "porcelain packages". I wanted to get the API of the "core" packages right and stable first before stabilizing the dependent "porcelain packages", because they are more important (are building blocks/enabler), less opinionated (almost 1:1 mapping to MIDI specs) and clearly limited/focused (limited to what is inside the MIDI specs). The APIs of the porcelain packages on the other hand dependent on the scope and use cases of the corresponding package which have to be defined and limited first.

Therefor I invite you to review the APIs of the core packages first (even the one's that I regard as "stable", because - as I didn't announce the midi package anywhere yet, my opinion about the stability may change if strong reasons appear and I would like to iron that out first). Also, please have a look at the open issues (there are open questions affecting the API).

That being said, concerning your points about the current API of midihandler:

- `*SMFPosition` vs `SMFPosition`: 
   The idea of the `midihandler` package is to provide a common way to deal with midi "live" messages as well as SMF events (messages with position).
   The callbacks for the meta messages all receive a `SMFPosition` because meta messages are only valid inside SMF files and the callbacks are only called, if a SMF file is read, so a `SMFPosition` will always be there.
   On the other hand, the channel message callbacks, the sysex message callbacks as well as the callbacks `Each` and `Unknown` are dealing with messages that may come from a live performance (`*SMFPosition == nil`) or from a SMF file (`SMFPosition != nil`). I think of the function signature with the pointer as a kind of reminder for the implementer to think about whether he needs to deal both live data and SMF data (i.e. check the `*SMFPosition == nil` case) or just with one of them. In the later case, when the input is only live data, *SMFPosition can be ignored and when the input is only SMF data, it can be relied on the fact that *SMFPosition will never be nil.

-  Concerning the `Logger` interface: Sadly the `log.Logger` of the standard
   lib is not an interface - otherwise I would have taken that. I wanted to make a minimal interface that is compatible with `log.Logger` and almost every logging library out there which clearly would not be the case with your proposal. 
 
Please tell me, if you still have objections and tell me how to update the docs to make this considerations more visible.

Thanks

**Comment by metakeule** [comment]
@kisielk 

Please have a look at the updated docs and example for midihandler.
Closing this ticket for now - if you still have objections, please reopen.
